// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJZVsIGtw4z4Oixay38s7rp66AKgqdNEU',
    appId: '1:750930693186:web:3084c329ef37d62fb2b1db',
    messagingSenderId: '750930693186',
    projectId: 'musicapplication-b265a',
    authDomain: 'musicapplication-b265a.firebaseapp.com',
    storageBucket: 'musicapplication-b265a.appspot.com',
    measurementId: 'G-E5269L3WZ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnrbiXp808RlH7ystHTYHOSOWy1WxLmQs',
    appId: '1:750930693186:android:592af32c8544839ab2b1db',
    messagingSenderId: '750930693186',
    projectId: 'musicapplication-b265a',
    storageBucket: 'musicapplication-b265a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeSqZZaZsGmVMcaVtJoeIBYPg-KrXDgeU',
    appId: '1:750930693186:ios:3e7c0c97f30b3b16b2b1db',
    messagingSenderId: '750930693186',
    projectId: 'musicapplication-b265a',
    storageBucket: 'musicapplication-b265a.appspot.com',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeSqZZaZsGmVMcaVtJoeIBYPg-KrXDgeU',
    appId: '1:750930693186:ios:3e7c0c97f30b3b16b2b1db',
    messagingSenderId: '750930693186',
    projectId: 'musicapplication-b265a',
    storageBucket: 'musicapplication-b265a.appspot.com',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJZVsIGtw4z4Oixay38s7rp66AKgqdNEU',
    appId: '1:750930693186:web:5f1cac1bf1bb7fc8b2b1db',
    messagingSenderId: '750930693186',
    projectId: 'musicapplication-b265a',
    authDomain: 'musicapplication-b265a.firebaseapp.com',
    storageBucket: 'musicapplication-b265a.appspot.com',
    measurementId: 'G-70F7H7ET57',
  );

}